steps:
- id: 'Terraform init'
  name: 'hashicorp/terraform:0.12.20'
  dir: 'terraform'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform init -input=false
      terraform workspace select scheduler-dataflow-demo || terraform workspace new scheduler-dataflow-demo
      terraform apply -input=false -var=project_id=${_PROJECT_ID} -var=region=${_REGION}\
        -var=bucket=${_BUCKET} -auto-approve
  waitFor: ['-']

- id: "Build dataflow template"
  name: 'python:3.8'
  dir: 'dataflow'
  env:
    - "PROJECT=${_PROJECT_ID}"
    - "BUCKET=${_BUCKET}"
    - "REGION=${_REGION}"
  entrypoint: /bin/sh
  args:
    - '-c'
    - 'pip install -r requirements.txt && python pipeline.py --input gs://${BUCKET}/data.csv --output gs://${BUCKET}/output --runner DataflowRunner --project ${PROJECT} --staging_location gs://${BUCKET}/staging --temp_location gs://${BUCKET}/temp --region ${REGION} --save_main_session'
  waitFor: ['Terraform init']
